---
openapi: 3.0.0
info:
  title: Test API Rest
  description: Description
  contact:
    email: you@your-company.com
  version: 1.0.0
servers:
- url: /
paths:
  /persons:
    get:
      summary: liste les personnes
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                example:
                - id: 1
                  firstName: tobi
                  lastName: uchiha
                  age: 24
                - id: 2
                  firstName: toba
                  lastName: uchihi
                  age: 33
                items:
                  $ref: '#/components/schemas/Person'
components:
  schemas:
    Person:
      type: object
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        age:
          type: integer
